# .scrutinizer.yml #
tools:
    external_code_coverage:
        timeout: 900
        runs: 7

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
    paths: {  }
